from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import WeatherViewSet, WeatherStatsView
from rest_framework.urlpatterns import format_suffix_patterns

# Create an instance of DefaultRouter and register the WeatherViewSet with 'weather' as the endpoint
router = DefaultRouter()
router.register(r'weather', WeatherViewSet, basename='weather')

# Define urlpatterns that includes the urls generated by the router
urlpatterns = [
    path('', include(router.urls)),
    path('stats/', WeatherStatsView.as_view(), name='weather-stats'),
]

# Use format_suffix_patterns to append a format suffix to URL patterns
urlpatterns = format_suffix_patterns(urlpatterns)
